# Master Key
unbind C-b
set -g prefix M-Space
bind M-Space send-prefix

# Navigation Keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize Panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Terminal
set -g default-terminal "xterm-256color"
set -g set-clipboard on

# Reload Config
bind r source-file ~/.tmux.conf

# Vi Copy Mode
setw -g mode-keys vi
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Window Indexing
set -g base-index 1
set -g renumber-windows on

# Pane Borders
set -g pane-border-lines heavy
set -g pane-border-style fg=#222222
set -g pane-active-border-style fg=#222222

# Dim Inactive Panes
set -g window-style bg=#1a1a1a
set -g window-active-style bg=terminal

# Status Bar
set -g status-bg '#222222'
set -g status-style bg=#222222,fg=#948ae3
set -g status-left-style fg=#948ae3,bold
set -g status-right-style fg=#948ae3
set -g window-status-current-style fg=#948ae3,bold
set -g window-status-style fg=#69676c

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# TPM Init (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
